apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: cloudgenius/fedora:24-demo
    name: fedora
    imagePullPolicy: Always
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: demo
          key: password
